apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: of38qqgos-go
  janus-idp.io/tekton: of38qqgos-go
  backstage.io/kubernetes-id: of38qqgos-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: of38qqgos-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
